# .graphclientrc.yml
sources:
  - name: barren-wuffet
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/psyf/bw-goerli-v1-0
# documents:
#   - ./src/example-query.graphql
